In [1]:
#스칼라
import torch

s1 = torch.tensor([1.])
print(s1)

s2 = torch.tensor([3.])
print(s2)

print(s1+s2)
print(s1-s2)
print(s1*s2)
print(s1/s2)

print(torch.add(s1,s2))
print(torch.sub(s1,s2))
print(torch.mul(s1,s2))
print(torch.div(s1, s2))

ImportError: numpy.core.multiarray failed to import

In [4]:
#벡터
v1 = torch.tensor([1., 2., 3.])
v2 = torch.tensor([4.,5.,6.])
print(torch.add(v1,v2))
print(torch.mul(v1, v2))
print(torch.div(v1, v2))
print(torch.dot(v1,v2))

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])
tensor(32.)


In [5]:
m1= torch.tensor(([1. ,2.], [3., 4.]))
m2= torch.tensor(([5., 6.], [7., 8.]))
print(torch.add(m1, m2))
print(torch.mul(m1, m2))
print(torch.div(m1, m2))
print(torch.matmul(m1, m2))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [7]:
if torch.cuda.is_available() :
    DEVICE = torch.device('cuda')
    print('cuda')
else :
    DEVICE = torch.device('cpu')
    print('cpu')

cpu


In [8]:
BATCH_SIZE = 64 #파라미터 업데이트 시 계산되는 데이터 갯수 -> 해당 갯수만큼 결괏값에 대한 오찻값 계산
INPUT_SIZE = 1000 #딥러닝 모델에서의 Input의 크기 및 입력층의 노드 수
HIDDEN_SIZE = 100 #은닉층의 노드 수
OUTPUT_SIZE = 10 #최종 출력 값 벡터 크기

In [14]:
# randn : 평균 0, 표준편차 1인 정규분포에서 값 샘플링
x = torch.randn(BATCH_SIZE,
                INPUT_SIZE,
                device = DEVICE,
                dtype=torch.float,
                requires_grad= False) # 모델의 Gradient 계산의 필요성)

y = torch.randn(BATCH_SIZE,
                OUTPUT_SIZE,
                device = DEVICE,
                dtype=torch.float,
                requires_grad= False)
#업데이트할 파라미터 값
w1 = torch.randn(INPUT_SIZE,
                HIDDEN_SIZE,
                device = DEVICE,
                dtype=torch.float,
                requires_grad= True)

w2 = torch.randn(HIDDEN_SIZE,
                OUTPUT_SIZE,
                device = DEVICE,
                dtype=torch.float,
                requires_grad= True)

In [17]:
#파라이터 업데이터 : Gradient 계산 결괏값 * learning_rate -> 을 이용해 업데이트됨.
learning_rate = 1e-6
for t in range(1, 501) :
    y_pred = x.mm(w1).clamp(min=0).mm(w2) #층과 층 사이에 비선형 함수 적용(clamp == ReLU())
    loss = (y_pred-y).pow(2).sum() #pow : 지수, pow(2) 제곱을 의미
    if t%100 == 0: #100번째마다 Loss 값을 계산
        print("Iteration: ",t, "\t", "Loss:", loss.item())

    loss.backward() #계산된 loss값을 사용하여 Back propagation 진행

    with torch.no_grad(): #grad 고정하고.
        w1 -= learning_rate*w1.grad #빼는 이유? Gradient 값에 대한 반대 방향으로 계산한다
        w2 -= learning_rate*w2.grad
        # gradient를 이용하여 업데이트 후, gradient 다시 초기화
        w1.grad.zero_()
        w2.grad.zero_()

Iteration:  100 	 Loss: 608.1271362304688
Iteration:  200 	 Loss: 2.117358922958374
Iteration:  300 	 Loss: 0.011795291677117348
Iteration:  400 	 Loss: 0.00024266699620056897
Iteration:  500 	 Loss: 3.8499030779348686e-05
