In [19]:
#스칼라
import torch

s1 = torch.tensor([1.])
print(s1)

s2 = torch.tensor([3.])
print(s2)

print(s1+s2)
print(s1-s2)
print(s1*s2)
print(s1/s2)

print(torch.add(s1,s2))
print(torch.sub(s1,s2))
print(torch.mul(s1,s2))
print(torch.div(s1, s2))

tensor([1.])
tensor([3.])
tensor([4.])
tensor([-2.])
tensor([3.])
tensor([0.3333])
tensor([4.])
tensor([-2.])
tensor([3.])
tensor([0.3333])


In [17]:
#벡터
v1 = torch.tensor([1., 2., 3.])
v2 = torch.tensor([4.,5.,6.])
print(torch.add(v1,v2))
print(torch.mul(v1, v2))
print(torch.div(v1, v2))
print(torch.dot(v1,v2))

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])
tensor(32.)


In [23]:
m1= torch.tensor(([1. ,2.], [3., 4.]))
m2= torch.tensor(([5., 6.], [7., 8.]))
print(torch.add(m1, m2))
print(torch.mul(m1, m2))
print(torch.div(m1, m2))
print(torch.matmul(m1, m2))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])
